[2024-10-02T17:25:17.681+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T17:25:17.700+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-10-05T00:00:00+00:00 [queued]>
[2024-10-02T17:25:17.708+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-10-05T00:00:00+00:00 [queued]>
[2024-10-02T17:25:17.709+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T17:25:17.889+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2023-10-05 00:00:00+00:00
[2024-10-02T17:25:17.895+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1264) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T17:25:17.896+0000] {standard_task_runner.py:63} INFO - Started process 1266 to run task
[2024-10-02T17:25:17.896+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2023-10-05T00:00:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpk76i0i18']
[2024-10-02T17:25:17.898+0000] {standard_task_runner.py:91} INFO - Job 37: Subtask transformar
[2024-10-02T17:25:17.945+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-10-05T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T17:25:18.017+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2023-10-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-05T00:00:00+00:00'
[2024-10-02T17:25:18.019+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T17:25:18.122+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T17:25:18.123+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline.py", line 17, in transformar
    df_agrupada = df.groupby('ContinentExp')[['cases', 'deaths']].sum().reset_index()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 8869, in groupby
    return DataFrameGroupBy(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/groupby/groupby.py", line 1278, in __init__
    grouper, exclusions, obj = get_grouper(
                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/groupby/grouper.py", line 1009, in get_grouper
    raise KeyError(gpr)
KeyError: 'ContinentExp'
[2024-10-02T17:25:18.133+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2023-10-05T00:00:00+00:00, execution_date=20231005T000000, start_date=20241002T172517, end_date=20241002T172518
[2024-10-02T17:25:18.144+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 37 for task transformar ('ContinentExp'; 1266)
[2024-10-02T17:25:18.190+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-02T17:25:18.207+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-02T17:25:18.211+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T18:57:15.876+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T18:57:15.909+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-10-05T00:00:00+00:00 [queued]>
[2024-10-02T18:57:15.919+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-10-05T00:00:00+00:00 [queued]>
[2024-10-02T18:57:15.920+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T18:57:16.209+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2023-10-05 00:00:00+00:00
[2024-10-02T18:57:16.223+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5307) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T18:57:16.224+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2023-10-05T00:00:00+00:00', '--job-id', '987', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp_rmax1gj']
[2024-10-02T18:57:16.232+0000] {standard_task_runner.py:91} INFO - Job 987: Subtask transformar
[2024-10-02T18:57:16.229+0000] {standard_task_runner.py:63} INFO - Started process 5329 to run task
[2024-10-02T18:57:16.318+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-10-05T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T18:57:16.443+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2023-10-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-05T00:00:00+00:00'
[2024-10-02T18:57:16.446+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T18:57:16.576+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T18:57:16.580+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T18:57:16.592+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2023-10-05T00:00:00+00:00, execution_date=20231005T000000, start_date=20241002T185715, end_date=20241002T185716
[2024-10-02T18:57:16.656+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T18:57:16.687+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T18:57:16.693+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
