[2024-10-02T17:25:14.779+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T17:25:14.814+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-10-06T00:00:00+00:00 [queued]>
[2024-10-02T17:25:14.825+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-10-06T00:00:00+00:00 [queued]>
[2024-10-02T17:25:14.826+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T17:25:15.140+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2023-10-06 00:00:00+00:00
[2024-10-02T17:25:15.147+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1233) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T17:25:15.150+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2023-10-06T00:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp52jya76u']
[2024-10-02T17:25:15.154+0000] {standard_task_runner.py:91} INFO - Job 31: Subtask transformar
[2024-10-02T17:25:15.152+0000] {standard_task_runner.py:63} INFO - Started process 1255 to run task
[2024-10-02T17:25:15.226+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-10-06T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T17:25:15.332+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2023-10-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-06T00:00:00+00:00'
[2024-10-02T17:25:15.334+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T17:25:15.576+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T17:25:15.577+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline.py", line 17, in transformar
    df_agrupada = df.groupby('ContinentExp')[['cases', 'deaths']].sum().reset_index()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 8869, in groupby
    return DataFrameGroupBy(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/groupby/groupby.py", line 1278, in __init__
    grouper, exclusions, obj = get_grouper(
                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/groupby/grouper.py", line 1009, in get_grouper
    raise KeyError(gpr)
KeyError: 'ContinentExp'
[2024-10-02T17:25:15.596+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2023-10-06T00:00:00+00:00, execution_date=20231006T000000, start_date=20241002T172514, end_date=20241002T172515
[2024-10-02T17:25:15.613+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 31 for task transformar ('ContinentExp'; 1255)
[2024-10-02T17:25:15.654+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-02T17:25:15.681+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-02T17:25:15.686+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T18:57:14.270+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T18:57:14.295+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-10-06T00:00:00+00:00 [queued]>
[2024-10-02T18:57:14.303+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-10-06T00:00:00+00:00 [queued]>
[2024-10-02T18:57:14.303+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T18:57:14.531+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2023-10-06 00:00:00+00:00
[2024-10-02T18:57:14.539+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5299) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T18:57:14.540+0000] {standard_task_runner.py:63} INFO - Started process 5304 to run task
[2024-10-02T18:57:14.541+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2023-10-06T00:00:00+00:00', '--job-id', '985', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpzy6nylhd']
[2024-10-02T18:57:14.546+0000] {standard_task_runner.py:91} INFO - Job 985: Subtask transformar
[2024-10-02T18:57:14.588+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-10-06T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T18:57:14.685+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2023-10-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-06T00:00:00+00:00'
[2024-10-02T18:57:14.686+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T18:57:14.813+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T18:57:14.815+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T18:57:14.823+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2023-10-06T00:00:00+00:00, execution_date=20231006T000000, start_date=20241002T185714, end_date=20241002T185714
[2024-10-02T18:57:14.875+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T18:57:14.885+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
