[2024-10-02T19:28:16.211+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-05-29T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
