[2024-10-02T17:31:42.783+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T17:31:42.819+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-06T00:00:00+00:00 [queued]>
[2024-10-02T17:31:42.832+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-06T00:00:00+00:00 [queued]>
[2024-10-02T17:31:42.832+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T17:31:43.149+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2024-09-06 00:00:00+00:00
[2024-10-02T17:31:43.158+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3096) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T17:31:43.161+0000] {standard_task_runner.py:63} INFO - Started process 3125 to run task
[2024-10-02T17:31:43.160+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2024-09-06T00:00:00+00:00', '--job-id', '624', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpdkh53tcu']
[2024-10-02T17:31:43.163+0000] {standard_task_runner.py:91} INFO - Job 624: Subtask transformar
[2024-10-02T17:31:43.226+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-06T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T17:31:43.350+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2024-09-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-06T00:00:00+00:00'
[2024-10-02T17:31:43.352+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T17:31:43.387+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T17:31:43.389+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline.py", line 13, in transformar
    df = pd.read_csv('data/dados_covid_extraidos.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 617, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1748, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 843, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 904, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 879, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 890, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2058, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 7201, saw 2

[2024-10-02T17:31:43.408+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2024-09-06T00:00:00+00:00, execution_date=20240906T000000, start_date=20241002T173142, end_date=20241002T173143
[2024-10-02T17:31:43.429+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 624 for task transformar (Error tokenizing data. C error: Expected 1 fields in line 7201, saw 2
; 3125)
[2024-10-02T17:31:43.456+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-02T17:31:43.487+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-02T17:31:43.498+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T18:55:27.747+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T18:55:27.811+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-06T00:00:00+00:00 [queued]>
[2024-10-02T18:55:28.273+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-06T00:00:00+00:00 [queued]>
[2024-10-02T18:55:28.274+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T18:55:28.309+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2024-09-06 00:00:00+00:00
[2024-10-02T18:55:28.317+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4983) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T18:55:28.318+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2024-09-06T00:00:00+00:00', '--job-id', '886', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpdx4sftg0']
[2024-10-02T18:55:28.328+0000] {standard_task_runner.py:63} INFO - Started process 5007 to run task
[2024-10-02T18:55:28.328+0000] {standard_task_runner.py:91} INFO - Job 886: Subtask transformar
[2024-10-02T18:55:28.432+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-06T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T18:55:28.631+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2024-09-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-06T00:00:00+00:00'
[2024-10-02T18:55:28.639+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T18:55:28.878+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T18:55:28.879+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T18:55:28.890+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2024-09-06T00:00:00+00:00, execution_date=20240906T000000, start_date=20241002T185527, end_date=20241002T185528
[2024-10-02T18:55:28.954+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T18:55:28.991+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T18:55:28.996+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T19:04:24.555+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T19:04:24.766+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-06T00:00:00+00:00 [queued]>
[2024-10-02T19:04:24.775+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-06T00:00:00+00:00 [queued]>
[2024-10-02T19:04:24.775+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T19:04:24.791+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2024-09-06 00:00:00+00:00
[2024-10-02T19:04:24.799+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=8222) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T19:04:24.801+0000] {standard_task_runner.py:63} INFO - Started process 8235 to run task
[2024-10-02T19:04:24.801+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2024-09-06T00:00:00+00:00', '--job-id', '1929', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp5znbt260']
[2024-10-02T19:04:24.805+0000] {standard_task_runner.py:91} INFO - Job 1929: Subtask transformar
[2024-10-02T19:04:24.852+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-06T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T19:04:24.986+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2024-09-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-06T00:00:00+00:00'
[2024-10-02T19:04:24.987+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T19:04:25.161+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T19:04:25.162+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T19:04:25.176+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2024-09-06T00:00:00+00:00, execution_date=20240906T000000, start_date=20241002T190424, end_date=20241002T190425
[2024-10-02T19:04:25.216+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T19:04:25.240+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T19:04:25.242+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
