[2024-10-02T17:28:40.545+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T17:28:40.570+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-04-21T00:00:00+00:00 [queued]>
[2024-10-02T17:28:40.578+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-04-21T00:00:00+00:00 [queued]>
[2024-10-02T17:28:40.578+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T17:28:40.770+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrair> on 2024-04-21 00:00:00+00:00
[2024-10-02T17:28:40.776+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2224) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T17:28:40.777+0000] {standard_task_runner.py:63} INFO - Started process 2238 to run task
[2024-10-02T17:28:40.777+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'extrair', 'scheduled__2024-04-21T00:00:00+00:00', '--job-id', '345', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp6zng9xby']
[2024-10-02T17:28:40.779+0000] {standard_task_runner.py:91} INFO - Job 345: Subtask extrair
[2024-10-02T17:28:40.818+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-04-21T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T17:28:40.892+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='extrair' AIRFLOW_CTX_EXECUTION_DATE='2024-04-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-21T00:00:00+00:00'
[2024-10-02T17:28:40.894+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T17:28:51.916+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T17:28:51.917+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline.py", line 9, in extrair
    df = pd.read_csv(url)
         ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 718, in get_handle
    ioargs = _get_filepath_or_buffer(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 377, in _get_filepath_or_buffer
    reader = BytesIO(req.read())
                     ^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 495, in read
    s = self._safe_read(self.length)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 642, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(4219403 bytes read, 87899 more expected)
[2024-10-02T17:28:51.927+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_covid_europa_pipeline, task_id=extrair, run_id=scheduled__2024-04-21T00:00:00+00:00, execution_date=20240421T000000, start_date=20241002T172840, end_date=20241002T172851
[2024-10-02T17:28:51.937+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 345 for task extrair (IncompleteRead(4219403 bytes read, 87899 more expected); 2238)
[2024-10-02T17:28:51.951+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-02T17:28:51.968+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-02T17:28:51.972+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T19:01:23.477+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T19:01:23.510+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-04-21T00:00:00+00:00 [queued]>
[2024-10-02T19:01:23.716+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-04-21T00:00:00+00:00 [queued]>
[2024-10-02T19:01:23.718+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T19:01:23.736+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrair> on 2024-04-21 00:00:00+00:00
[2024-10-02T19:01:23.743+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=7000) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T19:01:23.745+0000] {standard_task_runner.py:63} INFO - Started process 7017 to run task
[2024-10-02T19:01:23.746+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'extrair', 'scheduled__2024-04-21T00:00:00+00:00', '--job-id', '1535', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpvu_1uyzd']
[2024-10-02T19:01:23.748+0000] {standard_task_runner.py:91} INFO - Job 1535: Subtask extrair
[2024-10-02T19:01:23.805+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-04-21T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T19:01:23.897+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='extrair' AIRFLOW_CTX_EXECUTION_DATE='2024-04-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-21T00:00:00+00:00'
[2024-10-02T19:01:23.900+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T19:01:29.871+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T19:01:29.872+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T19:01:29.879+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=extrair, run_id=scheduled__2024-04-21T00:00:00+00:00, execution_date=20240421T000000, start_date=20241002T190123, end_date=20241002T190129
[2024-10-02T19:01:29.936+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T19:01:29.960+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T19:01:29.962+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T19:27:27.839+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T19:27:28.025+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-04-21T00:00:00+00:00 [queued]>
[2024-10-02T19:27:28.037+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-04-21T00:00:00+00:00 [queued]>
[2024-10-02T19:27:28.037+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T19:27:28.053+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrair> on 2024-04-21 00:00:00+00:00
[2024-10-02T19:27:28.060+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=10390) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T19:27:28.062+0000] {standard_task_runner.py:63} INFO - Started process 10402 to run task
[2024-10-02T19:27:28.063+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'extrair', 'scheduled__2024-04-21T00:00:00+00:00', '--job-id', '2555', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_agrupar_continente.py', '--cfg-path', '/tmp/tmpjzd89osu']
[2024-10-02T19:27:28.069+0000] {standard_task_runner.py:91} INFO - Job 2555: Subtask extrair
[2024-10-02T19:27:28.125+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-04-21T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T19:27:28.249+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='extrair' AIRFLOW_CTX_EXECUTION_DATE='2024-04-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-21T00:00:00+00:00'
[2024-10-02T19:27:28.251+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T19:27:37.779+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T19:27:37.780+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T19:27:37.789+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=extrair, run_id=scheduled__2024-04-21T00:00:00+00:00, execution_date=20240421T000000, start_date=20241002T192728, end_date=20241002T192737
[2024-10-02T19:27:37.901+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T19:27:37.924+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T19:27:37.927+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
