[2024-10-02T17:27:46.767+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T17:27:46.795+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-02-24T00:00:00+00:00 [queued]>
[2024-10-02T17:27:46.805+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-02-24T00:00:00+00:00 [queued]>
[2024-10-02T17:27:46.805+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T17:27:46.822+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrair> on 2024-02-24 00:00:00+00:00
[2024-10-02T17:27:46.831+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1904) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T17:27:46.832+0000] {standard_task_runner.py:63} INFO - Started process 1917 to run task
[2024-10-02T17:27:46.832+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'extrair', 'scheduled__2024-02-24T00:00:00+00:00', '--job-id', '242', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpwoyx_n9v']
[2024-10-02T17:27:46.834+0000] {standard_task_runner.py:91} INFO - Job 242: Subtask extrair
[2024-10-02T17:27:47.119+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-02-24T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T17:27:47.233+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='extrair' AIRFLOW_CTX_EXECUTION_DATE='2024-02-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-24T00:00:00+00:00'
[2024-10-02T17:27:47.235+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T17:27:58.296+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T17:27:58.297+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline.py", line 9, in extrair
    df = pd.read_csv(url)
         ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 718, in get_handle
    ioargs = _get_filepath_or_buffer(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 377, in _get_filepath_or_buffer
    reader = BytesIO(req.read())
                     ^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 495, in read
    s = self._safe_read(self.length)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 642, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(1829927 bytes read, 2477375 more expected)
[2024-10-02T17:27:58.308+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_covid_europa_pipeline, task_id=extrair, run_id=scheduled__2024-02-24T00:00:00+00:00, execution_date=20240224T000000, start_date=20241002T172746, end_date=20241002T172758
[2024-10-02T17:27:58.320+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 242 for task extrair (IncompleteRead(1829927 bytes read, 2477375 more expected); 1917)
[2024-10-02T17:27:58.360+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-02T17:27:58.379+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-02T17:27:58.383+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T19:00:01.953+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T19:00:01.975+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-02-24T00:00:00+00:00 [queued]>
[2024-10-02T19:00:02.144+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-02-24T00:00:00+00:00 [queued]>
[2024-10-02T19:00:02.144+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T19:00:02.157+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrair> on 2024-02-24 00:00:00+00:00
[2024-10-02T19:00:02.161+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=6465) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T19:00:02.162+0000] {standard_task_runner.py:63} INFO - Started process 6474 to run task
[2024-10-02T19:00:02.162+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'extrair', 'scheduled__2024-02-24T00:00:00+00:00', '--job-id', '1363', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp1d7k829a']
[2024-10-02T19:00:02.165+0000] {standard_task_runner.py:91} INFO - Job 1363: Subtask extrair
[2024-10-02T19:00:02.204+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-02-24T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T19:00:02.293+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='extrair' AIRFLOW_CTX_EXECUTION_DATE='2024-02-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-24T00:00:00+00:00'
[2024-10-02T19:00:02.295+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T19:00:08.334+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T19:00:08.343+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T19:00:08.362+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=extrair, run_id=scheduled__2024-02-24T00:00:00+00:00, execution_date=20240224T000000, start_date=20241002T190001, end_date=20241002T190008
[2024-10-02T19:00:08.611+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T19:00:08.654+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T19:00:08.663+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T19:26:20.878+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T19:26:20.909+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-02-24T00:00:00+00:00 [queued]>
[2024-10-02T19:26:21.124+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-02-24T00:00:00+00:00 [queued]>
[2024-10-02T19:26:21.125+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T19:26:21.145+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrair> on 2024-02-24 00:00:00+00:00
[2024-10-02T19:26:21.152+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=9913) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T19:26:21.153+0000] {standard_task_runner.py:63} INFO - Started process 9932 to run task
[2024-10-02T19:26:21.153+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'extrair', 'scheduled__2024-02-24T00:00:00+00:00', '--job-id', '2401', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpmb2gzdlq']
[2024-10-02T19:26:21.155+0000] {standard_task_runner.py:91} INFO - Job 2401: Subtask extrair
[2024-10-02T19:26:21.201+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-02-24T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T19:26:21.297+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='extrair' AIRFLOW_CTX_EXECUTION_DATE='2024-02-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-24T00:00:00+00:00'
[2024-10-02T19:26:21.300+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T19:26:29.802+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T19:26:29.803+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T19:26:29.810+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=extrair, run_id=scheduled__2024-02-24T00:00:00+00:00, execution_date=20240224T000000, start_date=20241002T192620, end_date=20241002T192629
[2024-10-02T19:26:29.921+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T19:26:29.943+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T19:26:29.947+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
