[2024-10-02T17:32:04.186+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T17:32:04.217+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-29T00:00:00+00:00 [queued]>
[2024-10-02T17:32:04.232+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-29T00:00:00+00:00 [queued]>
[2024-10-02T17:32:04.232+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T17:32:04.479+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2024-09-29 00:00:00+00:00
[2024-10-02T17:32:04.485+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3217) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T17:32:04.486+0000] {standard_task_runner.py:63} INFO - Started process 3231 to run task
[2024-10-02T17:32:04.486+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2024-09-29T00:00:00+00:00', '--job-id', '663', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpvev1x0pj']
[2024-10-02T17:32:04.489+0000] {standard_task_runner.py:91} INFO - Job 663: Subtask transformar
[2024-10-02T17:32:04.530+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-29T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T17:32:04.612+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-29T00:00:00+00:00'
[2024-10-02T17:32:04.613+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T17:32:04.638+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T17:32:04.639+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline.py", line 13, in transformar
    df = pd.read_csv('data/dados_covid_extraidos.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 617, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1748, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 843, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 904, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 879, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 890, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2058, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 7201, saw 2

[2024-10-02T17:32:04.651+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2024-09-29T00:00:00+00:00, execution_date=20240929T000000, start_date=20241002T173204, end_date=20241002T173204
[2024-10-02T17:32:04.665+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 663 for task transformar (Error tokenizing data. C error: Expected 1 fields in line 7201, saw 2
; 3231)
[2024-10-02T17:32:04.700+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-02T17:32:04.723+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-02T17:32:04.730+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T18:56:01.181+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T18:56:01.202+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-29T00:00:00+00:00 [queued]>
[2024-10-02T18:56:01.388+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-29T00:00:00+00:00 [queued]>
[2024-10-02T18:56:01.388+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T18:56:01.399+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2024-09-29 00:00:00+00:00
[2024-10-02T18:56:01.404+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5213) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T18:56:01.406+0000] {standard_task_runner.py:63} INFO - Started process 5219 to run task
[2024-10-02T18:56:01.406+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2024-09-29T00:00:00+00:00', '--job-id', '962', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpm3awul9s']
[2024-10-02T18:56:01.407+0000] {standard_task_runner.py:91} INFO - Job 962: Subtask transformar
[2024-10-02T18:56:01.447+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-29T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T18:56:01.523+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-29T00:00:00+00:00'
[2024-10-02T18:56:01.526+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T18:56:01.654+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T18:56:01.654+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T18:56:01.662+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2024-09-29T00:00:00+00:00, execution_date=20240929T000000, start_date=20241002T185601, end_date=20241002T185601
[2024-10-02T18:56:01.699+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T18:56:01.719+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T18:56:01.723+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T19:04:57.505+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T19:04:57.699+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-29T00:00:00+00:00 [queued]>
[2024-10-02T19:04:57.706+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-29T00:00:00+00:00 [queued]>
[2024-10-02T19:04:57.707+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T19:04:57.719+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2024-09-29 00:00:00+00:00
[2024-10-02T19:04:57.724+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=8456) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T19:04:57.726+0000] {standard_task_runner.py:63} INFO - Started process 8462 to run task
[2024-10-02T19:04:57.726+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2024-09-29T00:00:00+00:00', '--job-id', '2004', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpa36647_x']
[2024-10-02T19:04:57.729+0000] {standard_task_runner.py:91} INFO - Job 2004: Subtask transformar
[2024-10-02T19:04:57.773+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2024-09-29T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T19:04:57.856+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-29T00:00:00+00:00'
[2024-10-02T19:04:57.857+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T19:04:57.983+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T19:04:57.983+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T19:04:57.990+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2024-09-29T00:00:00+00:00, execution_date=20240929T000000, start_date=20241002T190457, end_date=20241002T190457
[2024-10-02T19:04:58.020+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T19:04:58.042+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T19:04:58.046+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
