[2024-10-02T17:29:42.598+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T17:29:42.620+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-06-12T00:00:00+00:00 [queued]>
[2024-10-02T17:29:42.628+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-06-12T00:00:00+00:00 [queued]>
[2024-10-02T17:29:42.629+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T17:29:42.826+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrair> on 2024-06-12 00:00:00+00:00
[2024-10-02T17:29:42.831+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2525) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T17:29:42.832+0000] {standard_task_runner.py:63} INFO - Started process 2535 to run task
[2024-10-02T17:29:42.832+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'extrair', 'scheduled__2024-06-12T00:00:00+00:00', '--job-id', '440', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpqvuylq1t']
[2024-10-02T17:29:42.834+0000] {standard_task_runner.py:91} INFO - Job 440: Subtask extrair
[2024-10-02T17:29:42.874+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-06-12T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T17:29:42.947+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='extrair' AIRFLOW_CTX_EXECUTION_DATE='2024-06-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-12T00:00:00+00:00'
[2024-10-02T17:29:42.948+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T17:29:50.198+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T17:29:50.199+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T17:29:50.207+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=extrair, run_id=scheduled__2024-06-12T00:00:00+00:00, execution_date=20240612T000000, start_date=20241002T172942, end_date=20241002T172950
[2024-10-02T17:29:50.228+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T17:29:50.255+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T17:29:50.258+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T19:02:24.896+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T19:02:24.923+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-06-12T00:00:00+00:00 [queued]>
[2024-10-02T19:02:25.112+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-06-12T00:00:00+00:00 [queued]>
[2024-10-02T19:02:25.113+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T19:02:25.130+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrair> on 2024-06-12 00:00:00+00:00
[2024-10-02T19:02:25.139+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=7441) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T19:02:25.141+0000] {standard_task_runner.py:63} INFO - Started process 7454 to run task
[2024-10-02T19:02:25.141+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'extrair', 'scheduled__2024-06-12T00:00:00+00:00', '--job-id', '1679', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpm87wfkv9']
[2024-10-02T19:02:25.143+0000] {standard_task_runner.py:91} INFO - Job 1679: Subtask extrair
[2024-10-02T19:02:25.192+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-06-12T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T19:02:25.278+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='extrair' AIRFLOW_CTX_EXECUTION_DATE='2024-06-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-12T00:00:00+00:00'
[2024-10-02T19:02:25.281+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T19:02:36.232+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T19:02:36.233+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline.py", line 9, in extrair
    df = pd.read_csv(url)
         ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 718, in get_handle
    ioargs = _get_filepath_or_buffer(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 377, in _get_filepath_or_buffer
    reader = BytesIO(req.read())
                     ^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 495, in read
    s = self._safe_read(self.length)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 642, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(3045367 bytes read, 1261935 more expected)
[2024-10-02T19:02:36.244+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_covid_europa_pipeline, task_id=extrair, run_id=scheduled__2024-06-12T00:00:00+00:00, execution_date=20240612T000000, start_date=20241002T190224, end_date=20241002T190236
[2024-10-02T19:02:36.257+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1679 for task extrair (IncompleteRead(3045367 bytes read, 1261935 more expected); 7454)
[2024-10-02T19:02:36.277+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-02T19:02:36.302+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-02T19:02:36.305+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
