[2024-10-02T17:26:39.273+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T17:26:39.299+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2023-12-30T00:00:00+00:00 [queued]>
[2024-10-02T17:26:39.307+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2023-12-30T00:00:00+00:00 [queued]>
[2024-10-02T17:26:39.307+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T17:26:39.480+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrair> on 2023-12-30 00:00:00+00:00
[2024-10-02T17:26:39.486+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1686) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T17:26:39.487+0000] {standard_task_runner.py:63} INFO - Started process 1700 to run task
[2024-10-02T17:26:39.487+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'extrair', 'scheduled__2023-12-30T00:00:00+00:00', '--job-id', '175', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpwyfiexo1']
[2024-10-02T17:26:39.489+0000] {standard_task_runner.py:91} INFO - Job 175: Subtask extrair
[2024-10-02T17:26:39.540+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2023-12-30T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T17:26:39.620+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='extrair' AIRFLOW_CTX_EXECUTION_DATE='2023-12-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-30T00:00:00+00:00'
[2024-10-02T17:26:39.622+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T17:26:46.175+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T17:26:46.177+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T17:26:46.187+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=extrair, run_id=scheduled__2023-12-30T00:00:00+00:00, execution_date=20231230T000000, start_date=20241002T172639, end_date=20241002T172646
[2024-10-02T17:26:46.238+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T17:26:46.265+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T17:26:46.267+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T18:58:48.020+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T18:58:48.049+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2023-12-30T00:00:00+00:00 [queued]>
[2024-10-02T18:58:48.279+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2023-12-30T00:00:00+00:00 [queued]>
[2024-10-02T18:58:48.279+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T18:58:48.299+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrair> on 2023-12-30 00:00:00+00:00
[2024-10-02T18:58:48.310+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=6015) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T18:58:48.311+0000] {standard_task_runner.py:63} INFO - Started process 6035 to run task
[2024-10-02T18:58:48.311+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'extrair', 'scheduled__2023-12-30T00:00:00+00:00', '--job-id', '1219', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpr77h645u']
[2024-10-02T18:58:48.313+0000] {standard_task_runner.py:91} INFO - Job 1219: Subtask extrair
[2024-10-02T18:58:48.384+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2023-12-30T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T18:58:48.484+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='extrair' AIRFLOW_CTX_EXECUTION_DATE='2023-12-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-30T00:00:00+00:00'
[2024-10-02T18:58:48.487+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T18:58:59.456+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T18:58:59.457+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline.py", line 9, in extrair
    df = pd.read_csv(url)
         ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 718, in get_handle
    ioargs = _get_filepath_or_buffer(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 377, in _get_filepath_or_buffer
    reader = BytesIO(req.read())
                     ^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 495, in read
    s = self._safe_read(self.length)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 642, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(3221099 bytes read, 1086203 more expected)
[2024-10-02T18:58:59.468+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_covid_europa_pipeline, task_id=extrair, run_id=scheduled__2023-12-30T00:00:00+00:00, execution_date=20231230T000000, start_date=20241002T185848, end_date=20241002T185859
[2024-10-02T18:58:59.479+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1219 for task extrair (IncompleteRead(3221099 bytes read, 1086203 more expected); 6035)
[2024-10-02T18:58:59.506+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-02T18:58:59.522+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-02T18:58:59.525+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T19:25:08.467+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T19:25:08.493+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2023-12-30T00:00:00+00:00 [queued]>
[2024-10-02T19:25:08.686+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2023-12-30T00:00:00+00:00 [queued]>
[2024-10-02T19:25:08.686+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T19:25:08.703+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrair> on 2023-12-30 00:00:00+00:00
[2024-10-02T19:25:08.711+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=9410) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T19:25:08.713+0000] {standard_task_runner.py:63} INFO - Started process 9424 to run task
[2024-10-02T19:25:08.713+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'extrair', 'scheduled__2023-12-30T00:00:00+00:00', '--job-id', '2237', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpr4ek85ug']
[2024-10-02T19:25:08.716+0000] {standard_task_runner.py:91} INFO - Job 2237: Subtask extrair
[2024-10-02T19:25:08.766+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2023-12-30T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T19:25:08.859+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='extrair' AIRFLOW_CTX_EXECUTION_DATE='2023-12-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-30T00:00:00+00:00'
[2024-10-02T19:25:08.862+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T19:25:14.070+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T19:25:14.071+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T19:25:14.077+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=extrair, run_id=scheduled__2023-12-30T00:00:00+00:00, execution_date=20231230T000000, start_date=20241002T192508, end_date=20241002T192514
[2024-10-02T19:25:14.094+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T19:25:14.113+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T19:25:14.115+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
